version: '3'
services:
  mysql:
    image: dev-mysql:latest
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./tmp/data:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
  myadmin:
    image: phpmyadmin/phpmyadmin:4.8
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "127.0.0.1:8081:80"
    environment:
      - PMA_HOST=mysql
    volumes:
      - ./tmp/data:/data
  postgres:
    image: dev-postgres:latest
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data:/data
  pgadmin:
    image: dpage/pgadmin4:latest 
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "127.0.0.1:8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@example.com
      - PGADMIN_DEFAULT_PASSWORD=dev
    volumes:
      - ./tmp/data:/data
  redis:
    image: dev-redis:latest
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./tmp/data:/data
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    volumes:
      - ./tmp/data:/data
        #  zipkin:
        #    image: openzipkin/zipkin
        #    restart: unless-stopped
        #    networks:
        #      - dev
        #    ports:
        #      - "127.0.0.1:9411:9411"
        #    volumes:
        #      - .:/data
        #  fluentd:
        #    image: fluent/fluentd:v1.2
        #    restart: unless-stopped
        #    networks:
        #      - dev
        #    ports:
        #      - "127.0.0.1:24224:24224"
        #      - "127.0.0.1:24224:24224/udp"
        #    volumes:
        #      - .:/data
        #      - ./log:/fluentd/log
        #  rabbitmq:
        #    image: rabbitmq:3.7-management-alpine
        #    restart: unless-stopped
        #    hostname: rabbitmq
        #    networks:
        #      - dev
        #    ports:
        #      - "127.0.0.1:5672:5672"
        #      - "127.0.0.1:8082:15672"
        #    environment:
        #      - RABBITMQ_ERLANG_COOKIE=0123456789
        #      - RABBITMQ_DEFAULT_USER=root
        #      - RABBITMQ_DEFAULT_PASS=root
        #      - RABBITMQ_DEFAULT_VHOST=/
        #    volumes:
        #      - .:/data
        
networks:
  dev:
    external:
      name: dev
